"""Create pizza models

Revision ID: 28fbdabae9c6
Revises:
Create Date: 2026-06-07 20:47:25.901895

"""
from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401 - needed for Alembic's autogenerate
from alembic import op  # noqa: F401 - needed for Alembic's autogenerate

# revision identifiers, used by Alembic.
revision: str = "28fbdabae9c6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
