"""Create pizza models

Revision ID: 3570b84d86f5
Revises: 91596e13a07d
Create Date: 2026-06-07 21:08:03.610069

"""
from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401 - needed for Alembic's autogenerate
from alembic import op  # noqa: F401 - needed for Alembic's autogenerate

# revision identifiers, used by Alembic.
revision: str = "3570b84d86f5"
down_revision: Union[str, Sequence[str], None] = "91596e13a07d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
