"""update dough ingredients

Revision ID: 68820172920a
Revises: a3decd80e456
Create Date: 2026-06-08 21:19:11.639545

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68820172920a"
down_revision: Union[str, Sequence[str], None] = "a3decd80e456"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("doughrecipe", schema=None) as batch_op:
        batch_op.add_column(sa.Column("water_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(
            sa.Column("salt_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="Iodized")
        )
        batch_op.add_column(sa.Column("salt_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(
            sa.Column("yeast_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default="Active Dry")
        )
        batch_op.add_column(sa.Column("yeast_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(
            sa.Column("sugar_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True, server_default="White")
        )
        batch_op.add_column(sa.Column("sugar_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(
            sa.Column("oil_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True, server_default="EVOO")
        )
        batch_op.add_column(sa.Column("oil_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column("poolish", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.add_column(sa.Column("parent_id", sa.Integer(), nullable=True))
        batch_op.drop_constraint(op.f("uq_doughrecipe_ingredients2"), type_="unique")
        batch_op.create_unique_constraint(
            op.f("uq_doughrecipe_ingredients3"),
            [
                "flour_type",
                "flour_description",
                "flour_grams",
                "water_grams",
                "water_description",
                "salt_type",
                "salt_description",
                "salt_grams",
                "yeast_grams",
                "sugar_type",
                "sugar_description",
                "sugar_grams",
                "oil_type",
                "oil_description",
                "oil_grams",
                "poolish",
                "notes",
            ],
        )
        batch_op.create_foreign_key("fk_doughrecipe_poolish", "doughrecipe", ["poolish"], ["id"])
        batch_op.create_foreign_key("fk_doughrecipe_parent_id", "doughrecipe", ["parent_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("doughrecipe", schema=None) as batch_op:
        batch_op.drop_constraint("fk_doughrecipe_poolish", type_="foreignkey")
        batch_op.drop_constraint("fk_doughrecipe_parent_id", type_="foreignkey")
        batch_op.drop_constraint("uq_doughrecipe_ingredients3", type_="unique")
        batch_op.create_unique_constraint(
            op.f("uq_doughrecipe_ingredients2"),
            [
                "flour_type",
                "flour_description",
                "flour_grams",
                "water_grams",
                "salt_grams",
                "yeast_grams",
                "sugar_grams",
                "oil_grams",
            ],
        )
        batch_op.drop_column("parent_id")
        batch_op.drop_column("created_at")
        batch_op.drop_column("notes")
        batch_op.drop_column("poolish")
        batch_op.drop_column("oil_description")
        batch_op.drop_column("oil_type")
        batch_op.drop_column("sugar_description")
        batch_op.drop_column("sugar_type")
        batch_op.drop_column("yeast_description")
        batch_op.drop_column("yeast_type")
        batch_op.drop_column("salt_description")
        batch_op.drop_column("salt_type")
        batch_op.drop_column("water_description")
    # ### end Alembic commands ###
