"""initial tables

Revision ID: 84db6a3f0620
Revises: e883b52bffc1
Create Date: 2026-06-07 21:11:51.535653

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84db6a3f0620"
down_revision: Union[str, Sequence[str], None] = "e883b52bffc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("doughrecipe")
    op.drop_table("pizzatopping")
    op.drop_table("rating")
    op.drop_table("pizza")
    op.drop_table("doughball")
    op.drop_table("bulkdough")
    op.drop_table("topping")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topping",
        sa.Column("description", sa.VARCHAR(), nullable=True),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "bulkdough",
        sa.Column("recipe_id", sa.INTEGER(), nullable=False),
        sa.Column("date_made", sa.DATETIME(), nullable=False),
        sa.Column("notes", sa.VARCHAR(), nullable=True),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["doughrecipe.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "doughball",
        sa.Column("bulk_dough_id", sa.INTEGER(), nullable=False),
        sa.Column("weight_grams", sa.INTEGER(), nullable=False),
        sa.Column("cold_fermentation", sa.BOOLEAN(), nullable=False),
        sa.Column("fermentation_time", sa.INTEGER(), nullable=True),
        sa.Column("proof_time", sa.INTEGER(), nullable=True),
        sa.Column("notes", sa.VARCHAR(), nullable=True),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["bulk_dough_id"], ["bulkdough.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pizza",
        sa.Column("name", sa.VARCHAR(), nullable=True),
        sa.Column("dough_ball_id", sa.INTEGER(), nullable=False),
        sa.Column("bake_time_seconds", sa.INTEGER(), nullable=True),
        sa.Column("bake_temperature_celsius", sa.INTEGER(), nullable=True),
        sa.Column("date_baked", sa.DATETIME(), nullable=True),
        sa.Column("notes", sa.VARCHAR(), nullable=True),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["dough_ball_id"], ["doughball.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rating",
        sa.Column("pizza_id", sa.INTEGER(), nullable=False),
        sa.Column("score", sa.FLOAT(), nullable=False),
        sa.Column("comment", sa.VARCHAR(), nullable=True),
        sa.Column("date_rated", sa.DATETIME(), nullable=False),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["pizza_id"], ["pizza.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pizzatopping",
        sa.Column("pizza_id", sa.INTEGER(), nullable=False),
        sa.Column("topping_name", sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(["pizza_id"], ["pizza.id"],),
        sa.ForeignKeyConstraint(["topping_name"], ["topping.name"],),
        sa.PrimaryKeyConstraint("pizza_id", "topping_name"),
    )
    op.create_table(
        "doughrecipe",
        sa.Column("flour_type", sa.VARCHAR(), nullable=False),
        sa.Column("flour_brand", sa.VARCHAR(), nullable=True),
        sa.Column("flour_grams", sa.FLOAT(), nullable=False),
        sa.Column("water_grams", sa.FLOAT(), nullable=False),
        sa.Column("salt_grams", sa.FLOAT(), nullable=False),
        sa.Column("yeast_grams", sa.FLOAT(), nullable=False),
        sa.Column("sugar_grams", sa.FLOAT(), nullable=True),
        sa.Column("oil_grams", sa.FLOAT(), nullable=True),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
