"""Create pizza models

Revision ID: 91596e13a07d
Revises: fd2614db813c
Create Date: 2026-06-07 21:04:12.910901

"""
from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401 - needed for Alembic's autogenerate
from alembic import op  # noqa: F401 - needed for Alembic's autogenerate

# revision identifiers, used by Alembic.
revision: str = "91596e13a07d"
down_revision: Union[str, Sequence[str], None] = "fd2614db813c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
