"""rename flour_model

Revision ID: a3decd80e456
Revises: 42f929f01266
Create Date: 2026-06-08 21:04:20.150252

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401 - needed for Alembic's autogenerate
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3decd80e456"
down_revision: Union[str, Sequence[str], None] = "42f929f01266"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("doughrecipe", schema=None) as batch_op:
        batch_op.drop_constraint(op.f("uq_doughrecipe_ingredients"), type_="unique")
        batch_op.create_unique_constraint(
            "uq_doughrecipe_ingredients2",
            [
                "flour_type",
                "flour_description",
                "flour_grams",
                "water_grams",
                "salt_grams",
                "yeast_grams",
                "sugar_grams",
                "oil_grams",
            ],
        )
        batch_op.drop_column("flour_brand")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("doughrecipe", schema=None) as batch_op:
        batch_op.add_column(sa.Column("flour_brand", sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint("uq_doughrecipe_ingredients2", type_="unique")
        batch_op.create_unique_constraint(
            op.f("uq_doughrecipe_ingredients"),
            [
                "flour_type",
                "flour_brand",
                "flour_grams",
                "water_grams",
                "salt_grams",
                "yeast_grams",
                "sugar_grams",
                "oil_grams",
            ],
        )
    # ### end Alembic commands ###
