"""initial tables

Revision ID: e883b52bffc1
Revises: 3570b84d86f5
Create Date: 2026-06-07 21:10:43.249294

"""
from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401 - needed for Alembic's autogenerate
from alembic import op  # noqa: F401 - needed for Alembic's autogenerate

# revision identifiers, used by Alembic.
revision: str = "e883b52bffc1"
down_revision: Union[str, Sequence[str], None] = "3570b84d86f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
