"""Create pizza models

Revision ID: fd2614db813c
Revises: 28fbdabae9c6
Create Date: 2026-06-07 20:56:24.454794

"""
from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401 - needed for Alembic's autogenerate
from alembic import op  # noqa: F401 - needed for Alembic's autogenerate

# revision identifiers, used by Alembic.
revision: str = "fd2614db813c"
down_revision: Union[str, Sequence[str], None] = "28fbdabae9c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
